# Generated by Django 5.1.2 on 2024-10-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
    ]
