# Generated by Django 5.1.2 on 2024-10-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
